<?php
// Minimal public index for the scaffold
// In a real Laravel app this file is generated by the framework (bootstrap, autoloading etc.).

http_response_code(200);
echo "<h1>GiftGenie Laravel scaffold</h1>\n";
echo "<p>This is a placeholder public/index.php. To run a real app, install Laravel with Composer and replace this file with the framework's public/index.php.</p>";
